export const INITIAL_DATA = {
  users: [
    { id: '1', name: 'Owner', email: 'owner@cafe.com', password: '123', role: 'owner' },
    { id: '2', name: 'Kitchen', email: 'kitchen@cafe.com', password: '123', role: 'kitchen' },
    { id: '3', name: 'Waiter', email: 'waiter@cafe.com', password: '123', role: 'waiter' }
  ],
  tables: Array.from({ length: 10 }, (_, i) => ({ id: `T${i + 1}`, label: `Table ${i + 1}`, qrCodeUrl: `/app/t/T${i + 1}`})),
  categories: [
    { id: 'c_starters', name: 'Starters', order: 1 },
    { id: 'c_soups', name: 'Soups', order: 2 },
    { id: 'c_veg', name: 'Veg Mains', order: 3 },
    { id: 'c_nonveg', name: 'Non-Veg Mains', order: 4 },
    { id: 'c_tandoor', name: 'Tandoor & Breads', order: 5 },
    { id: 'c_rice', name: 'Rice Sides', order: 6 },
    { id: 'c_biryani', name: 'Biryani', order: 7 },
    { id: 'c_snacks', name: 'Snacks', order: 8 },
    { id: 'c_beverages', name: 'Beverages', order: 9 },
    { id: 'c_desserts', name: 'Desserts', order: 10 },
    { id: 'c_combos', name: 'Combos', order: 11 }
  ],
  menuItems: [
    { 
      id: 'm_paneer_tikka', 
      name: 'Paneer Tikka', 
      name_hi: 'पनीर टिक्का',
      name_te: 'పనీర్ టిక్కా',
      categoryId: 'c_starters', 
      price: 320, 
      description: 'Cottage cheese cubes marinated in spiced yogurt and grilled in tandoor.', 
      description_hi: 'मसालेदार दही में मैरीनेट किए गए पनीर के टुकड़े, तंदूर में ग्रिल किए गए।',
      description_te: 'మసాలా పెరుగులో నానబెట్టిన పనీర్ ముక్కలు, తందూర్‌లో కాల్చబడినవి.',
      imageUrl: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&q=80&w=600', 
      available: true, 
      customizationOptions: ['Extra Mint Chutney', 'Double Cream Cheese', 'Less Spicy'],
      isVeg: true,
      isSpicy: 1,
      isBestseller: true,
      isChefSpecial: false,
      isNew: false,
      portionInfo: '6 Pcs',
      upsellIds: ['m_garlic_naan', 'm_mango_lassi', 'm_masala_papad']
    },
    { 
      id: 'm_hara_bhara', 
      name: 'Hara Bhara Kabab', 
      name_hi: 'हरा भरा कबाब',
      name_te: 'హరా భరా కబాబ్',
      categoryId: 'c_starters', 
      price: 280, 
      description: 'Crispy pan-fried patties made of spinach, green peas, and potatoes.', 
      description_hi: 'पालक, हरी मटर और आलू से बने कुरकुरे कबाब।',
      description_te: 'పాలకూర, పచ్చి బఠానీలు మరియు బంగాళాదుంపలతో చేసిన క్రిస్పీ కబాబ్స్.',
      imageUrl: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=600', 
      available: true, 
      customizationOptions: ['Less Oil', 'Extra Spicy'],
      isVeg: true,
      isSpicy: 0,
      isBestseller: false,
      isChefSpecial: true,
      isNew: false,
      portionInfo: '6 Pcs',
      upsellIds: ['m_fresh_lime', 'm_masala_papad']
    },
    { 
      id: 'm_chicken_65', 
      name: 'Chicken 65', 
      name_hi: 'चिकन 65',
      name_te: 'చికెన్ 65',
      categoryId: 'c_starters', 
      price: 350, 
      description: 'Spicy, deep-fried chicken cubes tempered with curry leaves and mustard seeds.', 
      description_hi: 'कढ़ी पत्ते और राई के साथ तड़का लगाया हुआ मसालेदार डीप-फ्राइड चिकन।',
      description_te: 'కరివేపాకు మరియు ఆవాలతో పోపు పెట్టిన స్పైసీ డీప్-ఫ్రైడ్ చికెన్ ముక్కలు.',
      imageUrl: 'https://images.unsplash.com/photo-1610057099443-fde8c4d90fef?auto=format&fit=crop&q=80&w=600', 
      available: true, 
      customizationOptions: ['Extra Curry Leaves', 'More Lemon Juice'],
      isVeg: false,
      isSpicy: 3,
      isBestseller: true,
      isChefSpecial: false,
      isNew: false,
      portionInfo: 'Plate',
      upsellIds: ['m_fresh_lime', 'm_mango_lassi']
    },
    { 
      id: 'm_tomato_shorba', 
      name: 'Tomato Shorba', 
      name_hi: 'टमाटर शोरबा',
      name_te: 'టమోటా షోర్బా',
      categoryId: 'c_soups', 
      price: 180, 
      description: 'Traditional Indian spiced tomato soup seasoned with roasted cumin.', 
      description_hi: 'भुने हुए जीरे से सजाया हुआ पारंपरिक भारतीय मसालेदार टमाटर का सूप।',
      description_te: 'వేయించిన జీలకర్రతో తయారుచేసిన సాంప్రదాయ భారతీయ మసాలా టమోటా సూప్.',
      imageUrl: 'https://images.unsplash.com/photo-1547592165-e1d17fed6006?auto=format&fit=crop&q=80&w=600', 
      available: true, 
      customizationOptions: ['Extra Croutons', 'Without Butter'],
      isVeg: true,
      isSpicy: 1,
      isBestseller: false,
      isChefSpecial: false,
      isNew: false,
      portionInfo: 'Bowl',
      upsellIds: ['m_masala_papad']
    },
    { 
      id: 'm_paneer_butter', 
      name: 'Paneer Butter Masala', 
      name_hi: 'पनीर बटर मसाला',
      name_te: 'పనీర్ బటర్ మసాలా',
      categoryId: 'c_veg', 
      price: 380, 
      description: 'Rich and creamy tomato-based gravy with cottage cheese cubes and butter.', 
      description_hi: 'पनीर के टुकड़ों और मक्खन के साथ समृद्ध और मलाईदार टमाटर आधारित ग्रेवी।',
      description_te: 'పనీర్ ముక్కలు మరియు వెన్నతో కూడిన రిచ్ మరియు క్రీమీ టమోటా గ్రేవీ.',
      imageUrl: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&q=80&w=600', 
      available: true, 
      customizationOptions: ['Less Butter', 'Extra Cream', 'Spicy'],
      isVeg: true,
      isSpicy: 1,
      isBestseller: true,
      isChefSpecial: false,
      isNew: false,
      portionInfo: 'Serves 2',
      upsellIds: ['m_butter_naan', 'm_jeera_rice', 'm_gulab_jamun']
    },
    { 
      id: 'm_dal_makhani', 
      name: 'Dal Makhani', 
      name_hi: 'दाल मखनी',
      name_te: 'దాల్ మఖానీ',
      categoryId: 'c_veg', 
      price: 340, 
      description: 'Slow-cooked black lentils and kidney beans with rich cream and butter.', 
      description_hi: 'मलाई और मक्खन के साथ धीमी आंच पर पकी हुई काली दाल और राजमा।',
      description_te: 'క్రీమ్ మరియు వెన్నతో తక్కువ మంటపై నెమ్మదిగా వండిన నల్ల మినుములు మరియు రాజ్మా.',
      imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600', 
      available: true, 
      customizationOptions: ['Without Butter', 'Less Cream'],
      isVeg: true,
      isSpicy: 0,
      isBestseller: false,
      isChefSpecial: true,
      isNew: false,
      portionInfo: 'Serves 2',
      upsellIds: ['m_garlic_naan', 'm_steamed_rice']
    },
    { 
      id: 'm_butter_chicken', 
      name: 'Butter Chicken', 
      name_hi: 'बटर चिकन',
      name_te: 'బటర్ చికెన్',
      categoryId: 'c_nonveg', 
      price: 420, 
      description: 'Tandoori chicken pieces cooked in a rich, buttery, creamy tomato sauce.', 
      description_hi: 'मक्खन और मलाईदार टमाटर सॉस में पकाया गया तंदूरी चिकन।',
      description_te: 'రిచ్, బటరీ, క్రీమీ టమోటా సాస్‌లో వండిన తందూరి చికెన్ ముక్కలు.',
      imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&q=80&w=600', 
      available: true, 
      customizationOptions: ['Boneless Only', 'Extra Butter', 'Spicy'],
      isVeg: false,
      isSpicy: 1,
      isBestseller: true,
      isChefSpecial: false,
      isNew: false,
      portionInfo: 'Serves 2',
      upsellIds: ['m_garlic_naan', 'm_jeera_rice', 'm_mango_lass']
    },
    { 
      id: 'm_lamb_rogan', 
      name: 'Lamb Rogan Josh', 
      name_hi: 'मटन रोगन जोश',
      name_te: 'లాంబ్ రోగన్ జోష్',
      categoryId: 'c_nonveg', 
      price: 490, 
      description: 'A classic Kashmiri lamb dish cooked with aromatic spices and yogurt gravy.', 
      description_hi: 'सुगंधित मसालों और दही की ग्रेवी के साथ पकाया गया क्लासिक कश्मीरी मटन व्यंजन।',
      description_te: 'సుగంధ ద్రవ్యాలు మరియు పెరుగు గ్రేవీతో వండిన క్లాసిక్ కాశ్మీరీ లాంబ్ వంటకం.',
      imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600', 
      available: true, 
      customizationOptions: ['Extra Spicy', 'Less Oil'],
      isVeg: false,
      isSpicy: 2,
      isBestseller: false,
      isChefSpecial: true,
      isNew: false,
      portionInfo: 'Serves 2',
      upsellIds: ['m_butter_naan', 'm_steamed_rice']
    },
    { 
      id: 'm_garlic_naan', 
      name: 'Garlic Naan', 
      name_hi: 'लहसुन नान',
      name_te: 'వెల్లుల్లి నాన్',
      categoryId: 'c_tandoor', 
      price: 80, 
      description: 'Leavened tandoor-baked flatbread brushed with garlic and butter.', 
      description_hi: 'लहसुन और मक्खन लगी हुई तंदूर में पकी हुई मैदे की रोटी।',
      description_te: 'వెల్లుల్లి మరియు వెన్న రాసిన తందూరి నాన్.',
      imageUrl: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=600', 
      available: true, 
      customizationOptions: ['Extra Butter', 'Crispy'],
      isVeg: true,
      isSpicy: 0,
      isBestseller: true,
      isChefSpecial: false,
      isNew: false,
      portionInfo: '1 Pc',
      upsellIds: ['m_masala_papad', 'm_mango_lassi']
    },
    { 
      id: 'm_butter_naan', 
      name: 'Butter Naan', 
      name_hi: 'मक्खन नान',
      name_te: 'బటర్ నాన్',
      categoryId: 'c_tandoor', 
      price: 70, 
      description: 'Traditional refined flour flatbread baked in tandoor and glazed with butter.', 
      description_hi: 'पारंपरिक तंदूर-बेक्ड नान जिसमें प्रचुर मात्रा में मक्खन लगाया गया हो।',
      description_te: 'తందూర్‌లో కాల్చి వెన్న పూసిన సాంప్రదాయ మైదా రొట్టె.',
      imageUrl: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=600', 
      available: true, 
      customizationOptions: ['Without Butter', 'Crispy'],
      isVeg: true,
      isSpicy: 0,
      isBestseller: false,
      isChefSpecial: false,
      isNew: false,
      portionInfo: '1 Pc',
      upsellIds: ['m_masala_papad', 'm_mango_lassi']
    },
    { 
      id: 'm_tandoori_roti', 
      name: 'Tandoori Roti', 
      name_hi: 'तंदूरी रोटी',
      name_te: 'తందూరి రోటీ',
      categoryId: 'c_tandoor', 
      price: 40, 
      description: 'Whole wheat flatbread baked in the traditional clay oven.', 
      description_hi: 'पारंपरिक मिट्टी के ओवन (तंदूर) में पकी हुई गेहूं की रोटी।',
      description_te: 'సాంప్రదాయ క్లే ఓవెన్ (తందూరి) లో కాల్చిన గోధుమ రొట్టె.',
      imageUrl: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=600', 
      available: true, 
      customizationOptions: ['With Butter', 'Without Butter'],
      isVeg: true,
      isSpicy: 0,
      isBestseller: false,
      isChefSpecial: false,
      isNew: false,
      portionInfo: '1 Pc',
      upsellIds: ['m_masala_papad']
    },
    { 
      id: 'm_jeera_rice', 
      name: 'Jeera Rice', 
      name_hi: 'जीरा चावल',
      name_te: 'జీరా రైస్',
      categoryId: 'c_rice', 
      price: 180, 
      description: 'Basmati rice tempered with cumin seeds and fresh coriander.', 
      description_hi: 'जीरा और ताजे धनिये के साथ तड़का लगाया हुआ बासमती चावल।',
      description_te: 'జీలకర్ర మరియు కొత్తిమీరతో పోపు పెట్టిన బాస్మతి బియ్యం.',
      imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600', 
      available: true, 
      customizationOptions: ['Double Cumin', 'Without Coriander'],
      isVeg: true,
      isSpicy: 0,
      isBestseller: false,
      isChefSpecial: false,
      isNew: false,
      portionInfo: 'Serves 2',
      upsellIds: ['m_dal_makhani']
    },
    { 
      id: 'm_steamed_rice', 
      name: 'Steamed Rice', 
      name_hi: 'स्टीम्ड चावल',
      name_te: 'స్టీమ్డ్ రైస్',
      categoryId: 'c_rice', 
      price: 140, 
      description: 'Long grain aromatic Basmati rice steamed to perfection.', 
      description_hi: 'पूरी तरह से स्टीम किया हुआ लंबा दाना बासमती चावल।',
      description_te: 'ఆవిరిపై ఉడికించిన పొడవైన బాస్మతి బియ్యం.',
      imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600', 
      available: true, 
      customizationOptions: ['Hot Served', 'Medium Portion'],
      isVeg: true,
      isSpicy: 0,
      isBestseller: false,
      isChefSpecial: false,
      isNew: false,
      portionInfo: 'Serves 2',
      upsellIds: ['m_dal_makhani', 'm_paneer_butter']
    },
    { 
      id: 'm_chicken_biryani', 
      name: 'Chicken Dum Biryani', 
      name_hi: 'चिकन दम बिरयानी',
      name_te: 'చికెన్ దమ్ బిరియాని',
      categoryId: 'c_biryani', 
      price: 390, 
      description: 'Fragrant basmati rice layered with marinated chicken, saffron, and mint, cooked on dum.', 
      description_hi: 'दम पर पकाया गया खुशबूदार बासमती चावल, मैरीनेटेड चिकन, केसर और पुदीना की परतें।',
      description_te: 'మసాలాతో నానబెట్టిన చికెన్, కుంకుమపువ్వు మరియు పుదీనాతో దమ్ చేసిన సుగంధ బాస్మతి రైస్.',
      imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&q=80&w=600', 
      available: true, 
      customizationOptions: ['Extra Salan', 'Double Raita', 'Leg Piece only'],
      isVeg: false,
      isSpicy: 2,
      isBestseller: true,
      isChefSpecial: false,
      isNew: false,
      portionInfo: 'Serves 1-2',
      upsellIds: ['m_mango_lassi', 'm_masala_papad']
    },
    { 
      id: 'm_veg_biryani', 
      name: 'Veg Dum Biryani', 
      name_hi: 'वेज दम बिरयानी',
      name_te: 'వెజ్ దమ్ బిరియాని',
      categoryId: 'c_biryani', 
      price: 320, 
      description: 'Aromatic basmati rice cooked with fresh seasonal vegetables and spices.', 
      description_hi: 'ताजी मौसमी सब्जियों और मसालों के साथ पकाया गया सुगंधित बासमती चावल।',
      description_te: 'తాజా కూరగాయలు మరియు మసాలాలతో వండిన సుగంధ బాస్మతి బియ్యం.',
      imageUrl: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&q=80&w=600', 
      available: true, 
      customizationOptions: ['Extra Veggies', 'Double Raita', 'Less Spicy'],
      isVeg: true,
      isSpicy: 1,
      isBestseller: false,
      isChefSpecial: false,
      isNew: false,
      portionInfo: 'Serves 1-2',
      upsellIds: ['m_mango_lassi', 'm_masala_papad']
    },
    { 
      id: 'm_samosa', 
      name: 'Vegetable Samosa', 
      name_hi: 'समोसा',
      name_te: 'సమోసా',
      categoryId: 'c_snacks', 
      price: 120, 
      description: 'Crispy pastry filled with spiced potatoes, peas, served with sweet & sour chutneys.', 
      description_hi: 'मसालेदार आलू और मटर से भरी हुई कुरकुरी समोसे की पेस्ट्री, चटनी के साथ।',
      description_te: 'బంగాళాదుంప, బఠానీలతో నింపిన క్రిస్పీ సమోసాలు, చట్నీలతో వడ్డించబడుతుంది.',
      imageUrl: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=600', 
      available: true, 
      customizationOptions: ['Extra Sweet Chutney', 'Hot Chilli Chutney'],
      isVeg: true,
      isSpicy: 1,
      isBestseller: false,
      isChefSpecial: false,
      isNew: false,
      portionInfo: '2 Pcs',
      upsellIds: ['m_masala_chai']
    },
    { 
      id: 'm_masala_papad', 
      name: 'Masala Papad', 
      name_hi: 'मसाला पापड़',
      name_te: 'మసాలా పాపడ్',
      categoryId: 'c_snacks', 
      price: 80, 
      description: 'Roasted papad topped with spicy onion, tomato, green chili, and lemon juice mixture.', 
      description_hi: 'भुना हुआ पापड़ जिसके ऊपर मसालेदार प्याज, टमाटर, हरी मिर्च और नींबू के रस का मिश्रण हो।',
      description_te: 'ఉల్లిపాయ, టమోటా, పచ్చిమిర్చి మరియు నిమ్మరసం మిశ్రమం పైన చల్లిన కాల్చిన పాపడ్.',
      imageUrl: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=600', 
      available: true, 
      customizationOptions: ['Without Onion', 'Less Chilli'],
      isVeg: true,
      isSpicy: 1,
      isBestseller: false,
      isChefSpecial: false,
      isNew: false,
      portionInfo: '2 Pcs',
      upsellIds: ['m_fresh_lime']
    },
    { 
      id: 'm_mango_lassi', 
      name: 'Mango Lassi', 
      name_hi: 'मैंगो लस्सी',
      name_te: 'మ్యాంగో లస్సీ',
      categoryId: 'c_beverages', 
      price: 150, 
      description: 'Creamy yogurt drink blended with sweet Alphonso mango pulp.', 
      description_hi: 'मीठे अल्फांसो आम के गूदे के साथ मिश्रित मलाईदार दही का पेय।',
      description_te: 'తీపి అల్ఫోన్సో మామిడి గుజ్జుతో కలిపిన క్రీమీ పెరుగు పానీయం.',
      imageUrl: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&q=80&w=600', 
      available: true, 
      customizationOptions: ['Less Sugar', 'Without Ice', 'Extra Mango Pulp'],
      isVeg: true,
      isSpicy: 0,
      isBestseller: true,
      isChefSpecial: false,
      isNew: false,
      portionInfo: 'Glass',
      upsellIds: ['m_gulab_jamun']
    },
    { 
      id: 'm_masala_chai', 
      name: 'Masala Chai', 
      name_hi: 'मसाला चाय',
      name_te: 'మసాలా చాయ్',
      categoryId: 'c_beverages', 
      price: 80, 
      description: 'Brewed black tea with milk and aromatic Indian spices like cardamom, ginger, cloves.', 
      description_hi: 'इलायची, अदरक, लौंग जैसे सुगंधित भारतीय मसालों और दूध के साथ बनी काली चाय।',
      description_te: 'యాలకులు, అల్లం, లవంగాలు వంటి సుగంధ ద్రవ్యాలు మరియు పాలు వేసి కాచిన నల్ల టీ.',
      imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=600', 
      available: true, 
      customizationOptions: ['Without Sugar', 'Sugar Free', 'More Ginger'],
      isVeg: true,
      isSpicy: 0,
      isBestseller: false,
      isChefSpecial: false,
      isNew: false,
      portionInfo: 'Cup',
      upsellIds: ['m_samosa']
    },
    { 
      id: 'm_fresh_lime', 
      name: 'Fresh Lime Soda', 
      name_hi: 'फ्रेश लाइम सोडा',
      name_te: 'ఫ్రెష్ లైమ్ సోడా',
      categoryId: 'c_beverages', 
      price: 110, 
      description: 'Refreshing soda drink served sweet, salted, or mixed with fresh lime juice.', 
      description_hi: 'ताजे नींबू के रस के साथ मीठा, नमकीन या मिश्रित परोसा जाने वाला स्फूर्तिदायक सोडा पेय।',
      description_te: 'నిమ్మరసంతో చేసిన రిఫ్రెషింగ్ సోడా డ్రింక్ (తీపి, ఉప్పు లేదా రెండు కలిపి వడ్డించబడుతుంది).',
      imageUrl: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&q=80&w=600', 
      available: true, 
      customizationOptions: ['Sweet', 'Salted', 'Mixed (Sweet & Salt)'],
      isVeg: true,
      isSpicy: 0,
      isBestseller: false,
      isChefSpecial: false,
      isNew: false,
      portionInfo: 'Glass',
      upsellIds: ['m_masala_papad']
    },
    { 
      id: 'm_gulab_jamun', 
      name: 'Gulab Jamun', 
      name_hi: 'गुलाब जामुन',
      name_te: 'గులాబ్ జామూన్',
      categoryId: 'c_desserts', 
      price: 140, 
      description: 'Warm, golden fried milk-solid dumplings soaked in green cardamom sugar syrup.', 
      description_hi: 'हरी इलायची की चाशनी में भीगे हुए गर्म, सुनहरे तले हुए मावे के गोले।',
      description_te: 'యాలకుల చక్కెర సిరప్‌లో నానబెట్టిన వేడి వేడి గులాబ్ జామూన్లు.',
      imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=600', 
      available: true, 
      customizationOptions: ['Served Warm', 'With Ice Cream (+₹50)'],
      isVeg: true,
      isSpicy: 0,
      isBestseller: true,
      isChefSpecial: false,
      isNew: false,
      portionInfo: '2 Pcs',
      upsellIds: ['m_mango_lassi']
    },
    { 
      id: 'm_kulfi', 
      name: 'Kesar Pista Kulfi', 
      name_hi: 'केसर पिस्ता कुल्फी',
      name_te: 'కేసర్ పిస్తా కుల్ఫీ',
      categoryId: 'c_desserts', 
      price: 160, 
      description: 'Traditional Indian dense frozen dessert flavored with saffron and pistachios.', 
      description_hi: 'केसर और पिस्ता के स्वाद वाली पारंपरिक भारतीय गाढ़ी जमी हुई आइसक्रीम।',
      description_te: 'కుంకుమపువ్వు మరియు పిస్తాపప్పుల రుచితో కూడిన సాంప్రదాయ భారతీయ కుల్ఫీ.',
      imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=600', 
      available: true, 
      customizationOptions: ['Sliced', 'On Stick'],
      isVeg: true,
      isSpicy: 0,
      isBestseller: false,
      isChefSpecial: true,
      isNew: false,
      portionInfo: 'Stick',
      upsellIds: ['m_gulab_jamun']
    },
    { 
      id: 'm_veg_thali', 
      name: 'Royal Veg Thali', 
      name_hi: 'शाही शाकाहारी थाली',
      name_te: 'రాయల్ వెజ్ థాలి',
      categoryId: 'c_combos', 
      price: 499, 
      description: 'Paneer Butter Masala, Dal Makhani, Mix Veg, Steamed Rice, 2 Roti, Gulab Jamun, and Papad.', 
      description_hi: 'पनीर बटर मसाला, दाल मखनी, मिक्स वेज, स्टीम्ड राइस, २ रोटी, गुलाब जामुन और पापड़।',
      description_te: 'పనీర్ బటర్ మసాలా, దాల్ మఖానీ, మిక్స్ వెజ్, అన్నం, 2 రోటీలు, గులాబ్ జామూన్ మరియు పాపడ్.',
      imageUrl: 'https://images.unsplash.com/photo-1585238342024-78d387f4a707?auto=format&fit=crop&q=80&w=600', 
      available: true, 
      customizationOptions: ['Butter Naan (+₹20)', 'Without Onion & Garlic'],
      isVeg: true,
      isSpicy: 1,
      isBestseller: false,
      isChefSpecial: false,
      isNew: true,
      portionInfo: '1 Thali',
      upsellIds: ['m_mango_lassi']
    },
    { 
      id: 'm_chicken_thali', 
      name: 'Maharaja Chicken Thali', 
      name_hi: 'महाराजा चिकन थाली',
      name_te: 'మహారాజా చికెన్ థాలి',
      categoryId: 'c_combos', 
      price: 549, 
      description: 'Butter Chicken, Dal Makhani, Steamed Rice, 1 Garlic Naan, 1 Roti, Gulab Jamun, and Papad.', 
      description_hi: 'बटर चिकन, दाल मखनी, स्टीम्ड राइस, १ लहसुन नान, १ रोटी, गुलाब जामुन और पापड़।',
      description_te: 'బటర్ చికెన్, దాల్ మఖానీ, అన్నం, 1 వెల్లుల్లి నాన్, 1 రోటీ, గులాబ్ జామూన్ మరియు పాపడ్.',
      imageUrl: 'https://images.unsplash.com/photo-1585238342024-78d387f4a707?auto=format&fit=crop&q=80&w=600', 
      available: true, 
      customizationOptions: ['Double Butter Chicken', 'Less Spicy'],
      isVeg: false,
      isSpicy: 1,
      isBestseller: false,
      isChefSpecial: false,
      isNew: true,
      portionInfo: '1 Thali',
      upsellIds: ['m_mango_lassi']
    }
  ],
  orders: [],
  waiterCalls: []
};
